config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

 
  devise_for :users
  root 'users#home'

  resources :users
  resources :works

#match ':controller(/:action(/:id))', :via => :get

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)


    user ||= User.new
    if user.admin?
        can :manage, :all
    else

        can :update, Work do |work|
            work.user == user
        end

        can :destroy, Work do |work|
            work.user == user
        end


        can :create, Work
        
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  enum role: [:user, :manager]
  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
  	self.role ||= :user
  end

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

   has_many :works, dependent: :destroy
   
end

app/models/work.rb
class Work < ApplicationRecord

	belongs_to :user
	
end

app/models/work_search.rb
class WorkSearch
	attr_reader :date_from, :date_to

	def initialize(params)
		params ||= {}
		@date_from = parsed_date(params[:date_from], 30.days.ago.to_date.to_s)
		@date_to = parsed_date(params[:date_to], Date.today.to_s)	
	end

	def scope
		Work.where('date BETWEEN ? AND ?', @date_from, @date_to )
	end

	private

	def parsed_date(date_string, default)
		Date.parse(date_string)
	rescue ArgumentError, TypeError
		default
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

 rescue_from CanCan::AccessDenied do |exception|
    flash[:error] = exception.message
    redirect_to root_url
  end

  protected

  def configure_permitted_parameters
  	devise_parameter_sanitizer.permit(:sign_up, keys: [:firstname,:lastname, :email, :password  ])
  	devise_parameter_sanitizer.permit(:account_update, keys: [:firstname,:lastname,:project, :email, :password, :current_password ])  
  end

	private
	
	def user_not_authorized
			flash[:alert] = "Access Denied."
			redirect_to (request.referrer || root_path)
		end	


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_filter :authenticate_user!
	#after_action :verify_authorized


  def home
  	if current_user
  		redirect_to works_path
  	end
  end

  def index
  	@users = User.all
  	authorize User
  end

  def show
  	@user = User.find(params[:id])
  	authorize @user
  end

  def edit
  	@user = User.find(params[:id])
  end

  def destroy
  	user = User.find(params[:id])
  	authorize user
  	user.destroy
  	redirect_to users_path, :notice => "User deleted"
  end

  def update
  	@user = User.find(params[:id])
  	authorize @user

  	if @user.update_attributes(secure_params)
  		redirect_to users_path, :success=> 'User updated'  		
  	else
  		redirect_to users_path, :alert => 'Unable to update '
  	end
  end

  private

  def secure_params
  	params.require(:user).permit(:firstname, :lastname, :project, :role)
  	
  end





end

app/controllers/works_controller.rb
class WorksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_work, only: [:show, :edit, :update, :destroy]

  # GET /works
  # GET /works.json
  def index
    #@works = current_user.works //show users work only
    @search = WorkSearch.new(params[:search])
    @works = @search.scope

  end

  # GET /works/1
  # GET /works/1.json
  def show
  end

  # GET /works/new
  def new
    @work = Work.new
  end

  # GET /works/1/edit
  def edit
  end

  # POST /works
  # POST /works.json
  def create
    @work = current_user.works.new(work_params)

    respond_to do |format|
      if @work.save
        format.html { redirect_to @work, notice: 'Work was successfully created.' }
        format.json { render :show, status: :created, location: @work }
      else
        format.html { render :new }
        format.json { render json: @work.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /works/1
  # PATCH/PUT /works/1.json
  def update
    respond_to do |format|
      if @work.update(work_params)
        format.html { redirect_to @work, notice: 'Work was successfully updated.' }
        format.json { render :show, status: :ok, location: @work }
      else
        format.html { render :edit }
        format.json { render json: @work.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /works/1
  # DELETE /works/1.json
  def destroy
    @work.destroy
    respond_to do |format|
      format.html { redirect_to works_url, notice: 'Work was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_work
      @work = Work.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def work_params
      params.require(:work).permit(:issue, :date, :hour, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/works_helper.rb
module WorksHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Home", root_path, class: "navbar-brand" %>
      <%= link_to "Issues", works_path, class: "navbar-brand" %>
      <%= link_to "Users", users_path, class: "navbar-brand" %>
    

    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      
      
      <ul class="nav navbar-nav navbar-right">
      <% if current_user %>

      <li><%= link_to "Logged in as: #{current_user.firstname}" , user_path(current_user) %></li>
      <li><%= link_to "Edit your Profile", edit_user_registration_path  %></li>
      <li><%= link_to "Logout", destroy_user_session_path, method: :delete  %></li>
      <% else %>
      <li><%= link_to "Sign Up", new_user_registration_path  %></li>
      <li><%= link_to "Login", new_user_session_path  %></li>
      <% end %>
        
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SimpleTimeMgmt</title>
   
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
   <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  </head>

  <body>
  <%=  render "layouts/header" %>
  <div class="container">
    <%= yield %>
    </div>
  </body>
</html>

app/views/users/_form.html.erb
<%= simple_form_for(@user) do |f| %>
  <%#= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :firstname %>
    <%= f.input :lastname %>
    <%= f.input :project %>
    
    <%= f.select(:role, User.roles.keys.map {|role| [role.titleize,role]}) %>
   
    <%#= f.input :description %>
  </div>

  <div class="form-actions">
  <br />
    <%= f.button :submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<td>
  <%= user.firstname + " " + user.lastname %>
</td>
<td>
  <%= link_to user.email, user %>
</td>
<td>
  <%= user.project %>
</td>
<td>
  <%= form_for(user) do |f| %>
    <%= f.select(:role, User.roles.keys.map {|role| [role.titleize,role]}) %>
    <td>
	<%= f.submit 'Change Role', class: "btn btn-primary" %>
    </td>
  <% end %>
</td>
<td><%= link_to 'Edit', edit_user_path(user), class: "btn btn-primary" %></td>
<td>
  <%= link_to("Delete user", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, class: "btn btn-primary") unless user == current_user %>
</td>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/home.html.erb
<div class="jumbotron">
  <h1>Time Management System</h1>
  <p>Sign up or Login to your account</p>
  <%= link_to "Sign Up", new_user_registration_path , class: "btn btn-primary btn-lg"  %>
</div>

app/views/users/index.html.erb
<div class="bigbox">
  <div class="box">
    <table class="table table-bordered">
    <thead>
    <tr>
      <th>Name</th>
      <th>email</th>
      <th>Project</th>
      <th>Role</th>
      <th colspan="3"></th>
    </tr>
  </thead>
      <tbody>
        <% @users.each do |user| %>
          <tr>
            <%= render user %>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/users/show.html.erb
<h3>User</h3>
<p>Name: <%= @user.firstname + " " + @user.lastname if @user.firstname %></p>
<p>Project: <%= @user.project if @user.project %></p>
<p>Email: <%= @user.email if @user.email %></p>
<p> <%= @user.role if @user.role %></p>

app/views/works/_form.html.erb
<%= simple_form_for(@work) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :issue %>
    <%= f.input :date %>
    <%= f.input :hour %>
    <%= f.input :description %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/works/edit.html.erb
<h1>Editing Work</h1>

<%= render 'form', work: @work %>

<%= link_to 'Show', @work %> |
<%= link_to 'Back', works_path %>

app/views/works/index.html.erb
<p id="notice"><%= notice %></p>
<div class="row" >
  <h1>Time Entries</h1> 
    <div class="pull-right range-query">
    <h4>Select Date</h4>
      <%= form_tag works_path, method: :get do  %>
      <h5><strong> From  &nbsp; &nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;To </h5>
        <%= date_field_tag 'search[date_from]', @search.date_from %>

        <%= date_field_tag 'search[date_to]', @search.date_to %>
        <%= submit_tag 'search', class: 'btn search-button' %>
      <% end %>
    </div>
  </div>





<table class="table table-bordered">
  <thead>
    <tr>
      <th>Date</th>
      <th>Author</th>
      <th>Issue</th>
      <th>Hour</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @works.each do |work| %>
      <tr>
      <td><%= work.date %></td>
        <td><%= work.user.firstname + " " + work.user.lastname %></td>
        <td><%= work.issue %></td>
        <td><%= work.hour %></td>
        <td><%= work.description %></td>
        </strong>
        <td><%= link_to 'Show', work %></td>
        <% if can? :update, work %>
        <td><%= link_to 'Edit', edit_work_path(work) %></td>
        <% end %>
         <% if can? :destroy, work %>
        <td><%= link_to 'Delete', work, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Add New Issue', new_work_path, class: "btn btn-primary" %>

app/views/works/new.html.erb
<h1>New Work</h1>

<%= render 'form', work: @work %>

<%= link_to 'Back', works_path %>

app/views/works/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Issue:</strong>
  <%= @work.issue %>
</p>

<p>
  <strong>Done by:</strong>
  <%= @work.user.firstname + " " + @work.user.lastname %>
</p>

<p>
  <strong>Date:</strong>
  <%= @work.date %>
</p>

<p>
  <strong>Hour:</strong>
  <%= @work.hour %>
</p>

<p>
  <strong>Description:</strong>
  <%= @work.description %>
</p>
<% if can? :update, @work %>
<%= link_to 'Edit', edit_work_path(@work) %> |
<% end %>
<%= link_to 'Back', works_path %>